### ISSUE TITLE
软件很好用，好的建议可以留在这里，让作者看见

### ISSUE THREAD

**Issue by kshq1996** [aitexiaoy/Strawberry-Wallpaper#10]
软件很好用，好的建议可以留在这里，让作者看见

**Comment by kshq1996** [comment]
1、能否出一个只下载不设置桌面壁纸的按钮
2、能否出一个裁剪手机壁纸的按钮
3、不知道国内有没有好点的图片源，国外的都比较慢搜索中文关键字不能匹配上

**Comment by aitexiaoy** [comment]
> 1，能否出一个只下载不设置桌面壁纸的按钮
> 2，能否出一个裁剪手机壁纸的按钮
> 3，不知道国内有没有好点的图片来源，国外的都比较慢搜索中文关键字不能匹配上

感谢使用与支持
前两项功能可以考虑一下，没准在那个版本上就增加了，请敬请期待。
针对关键词搜索，会用百度翻译将中文转成英文，但是百度翻译有的时候翻译出来的不靠谱。

**Comment by kshq1996** [comment]
> > 1，能否出一个只下载不设置桌面壁纸的按钮
> > 2，能否出一个裁剪手机壁纸的按钮
> > 3，不知道国内有没有好点的图片来源，国外的都比较慢搜索中文关键字不能匹配上
> 
> 感谢使用与支持
> 前两项功能可以考虑一下，没准在那个版本上就增加了，请敬请期待。
> 针对关键词搜索，会用百度翻译将中文转成英文，但是百度翻译有的时候翻译出来的不靠谱。

谢谢采纳，感谢无私的付出

**Comment by aitexiaoy** [comment]
v1.4.0版本已发布，部分功能已经增加上。感谢支持。以后有好的建议可以去[这个issues](https://github.com/aitexiaoy/Strawberry-Wallpaper/issues/1)下面留言。感谢支持。
