### ISSUE TITLE
mac command q无反应，这个可以修复吗，这些全局快捷健

### ISSUE THREAD

**Issue by lk0606** [aitexiaoy/Strawberry-Wallpaper#14]

**Comment by aitexiaoy** [comment]
command q是什么快捷键？

**Comment by aitexiaoy** [comment]
目前草莓不支持快捷键

**Comment by lk0606** [comment]
这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗

**Comment by aitexiaoy** [comment]
> 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗

electron或者还有一个另一个

**Comment by lk0606** [comment]
> > 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗
> 
> electron或者还有一个另一个

是什么

**Comment by aitexiaoy** [comment]
> > > 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗
> > 
> > 
> > electron或者还有一个另一个
> 
> 是什么

nw.js

**Comment by lk0606** [comment]
> > > > 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗
> > > 
> > > 
> > > electron或者还有一个另一个
> > 
> > 
> > 是什么
> 
> nw.js

哪个会更好用一些，或者说更流行。electron吗？你这个是用什么开发的

**Comment by aitexiaoy** [comment]
> > > > > 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗
> > > > 
> > > > 
> > > > electron或者还有一个另一个
> > > 
> > > 
> > > 是什么
> > 
> > 
> > nw.js
> 
> 哪个会更好用一些，或者说更流行。electron吗？你这个是用什么开发的

同学，这个你搜一下吧。我也给不了你比较专业的解答。

**Comment by lk0606** [comment]
> > > > > > 这款应用是用什么语言或框架开发的，如果前端人员想开发dmg的话，用什么开发，electron吗
> > > > > 
> > > > > 
> > > > > electron或者还有一个另一个
> > > > 
> > > > 
> > > > 是什么
> > > 
> > > 
> > > nw.js
> > 
> > 
> > 哪个会更好用一些，或者说更流行。electron吗？你这个是用什么开发的
> 
> 同学，这个你搜一下吧。我也给不了你比较专业的解答。

好吧好吧
