### ISSUE TITLE
 brew cask install strawberry-wallpaper 下载失败

### ISSUE THREAD

**Issue by DieYoungWsn** [aitexiaoy/Strawberry-Wallpaper#28]
==> Downloading http://sw.taoacat.com/Strawberry%20Wallpaper-mac.dmg

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'strawberry-wallpaper' with message: Download failed: http://sw.taoacat.com/Strawberry%20Wallpaper-mac.dmg

**Comment by Jilingwei** [comment]
下载地址挂了

**Comment by aitexiaoy** [comment]
阿里云没费了
