### ISSUE TITLE
更新V1.1.1后，点击图片中设置壁纸，设置壁纸不成功

### ISSUE THREAD

**Issue by Nykuo-INN** [aitexiaoy/Strawberry-Wallpaper#5]
更新V1.1.1后，点击图片中设置壁纸，设置壁纸不成功
![Uploading 图片1.png…]()

**Comment by aitexiaoy** [comment]
重启一下软件试试

**Comment by Nykuo-INN** [comment]
找到问题所在了，图片的保存地址没有设置好，重新设置了一个文件夹，可以成功的下载和更换壁纸了


| |
奈姻恳
|
|
gao7057827@163.com
|
签名由网易邮箱大师定制
在2019年6月26日 15:40，aitexiaoy<notifications@github.com> 写道：

重启一下软件试试
