### ISSUE TITLE
mac 分屏只更新一块屏幕壁纸

### ISSUE THREAD

**Issue by youkongling** [aitexiaoy/Strawberry-Wallpaper#6]

**Comment by aitexiaoy** [comment]
是在2个显示器下，只更新一个显示器的壁纸吗？

**Comment by youkongling** [comment]
对的，我的mac连接了一个戴尔的显示器，然后戴尔的屏幕更新了壁纸，mac主屏幕没更新

**Comment by youkongling** [comment]
然后我刚刚手动测试了下，如果你手动在那个屏幕下面选择设置壁纸，那它只更新当前屏幕的壁纸，两个屏幕得分别操作一次，自动更新就是只更新一个

**Comment by aitexiaoy** [comment]
ok，这个问题我遇到过，另外还有个在mac下自动更新可能会更新失败的问题。

**Comment by aitexiaoy** [comment]
这个问题的原因是这样的：在mac下如果多个屏幕打开了多个窗口，窗口都是全屏窗口。那所打开的全屏窗口下壁纸可能会设置不上，如果关闭全屏窗口，或者打开空的窗口就能设置成功。
可以参考这个上面的讨论：https://github.com/sindresorhus/macos-wallpaper/issues/4
我直接执行swift设置壁纸也会有这个问题
