### ISSUE TITLE
mac下壁纸不自动更新 重启后无法崩溃

### ISSUE THREAD

**Issue by youkongling** [aitexiaoy/Strawberry-Wallpaper#7]
![image](https://user-images.githubusercontent.com/20356228/60325299-9340ae80-99b9-11e9-80ec-19adbb23ca5e.png)
今天壁纸没有更新，更换不成功后重启应用，出现上方界面，无法操作，僵硬

**Comment by youkongling** [comment]
关机重启后恢复正常，稍显不稳定。。

**Comment by aitexiaoy** [comment]
切换图库呢，这个可能不是崩溃。提示这个一般是请求接口

**Comment by youkongling** [comment]
时间好长，等了2-3min没反应

**Comment by aitexiaoy** [comment]
你本地有抓包软件吗，方便抓包看看请求吗？

**Comment by youkongling** [comment]
晚上回去弄下，看下我能复现不

**Comment by aitexiaoy** [comment]
你好，我知道问题了，pexels接口地址更改了。原接口获取不到图片了。

**Comment by aitexiaoy** [comment]
在版本1.2.0中已修复次Bug
