### ISSUE TITLE
500px 壁纸模糊，像素不高

### ISSUE THREAD

**Issue by youkongling** [aitexiaoy/Strawberry-Wallpaper#9]
今天更新成了1.3.2，使用500px作为图源的时候，每张图片的像素都有点低，很模糊
![image](https://user-images.githubusercontent.com/20356228/68658392-517f6180-0570-11ea-84c6-18ae8a4ae41a.png)
![Uploading image.png…]()
示例图上是好的

**Comment by aitexiaoy** [comment]
> 今天更新成了1.3.2，使用500px作为图源的时候，每张图片的像素都有点低，很模糊
> 
> 
> 示例图上是好的

嗯，我发现好像是有这个问题，有时间的时候我看一下，最近一段时间比较忙。感谢你的支持以及建议。

**Comment by aitexiaoy** [comment]
版本1.3.3已修复
